# Generated by Django 3.2.9 on 2021-11-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ud_app', '0005_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
