# Generated by Django 3.2.9 on 2021-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ud_app', '0006_rename_variations_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='ud_app.Variation'),
        ),
    ]
